CREATE TABLE USERS (
ID         VARCHAR(36) PRIMARY KEY NOT NULL,
LOGIN      VARCHAR NOT NULL,
PASSWORD   VARCHAR NOT NULL,
PHONE      VARCHAR(12),
EMAIL      VARCHAR,
POST       VARCHAR(30)
);

CREATE TABLE HANDBOOK (
HBDATAVERID     INTEGER PRIMARY KEY NOT NULL,
NAME            VARCHAR,
DESCRIPTION     VARCHAR,
STRINGFIELD00   VARCHAR,
STRINGFIELD01   VARCHAR,
STRINGFIELD02   VARCHAR,
STRINGFIELD03   VARCHAR,
STRINGFIELD04   VARCHAR,
STRINGFIELD05   VARCHAR,
STRINGFIELD06   VARCHAR,
STRINGFIELD07   VARCHAR,
STRINGFIELD08   VARCHAR,
STRINGFIELD09   VARCHAR,
STRINGFIELD10   VARCHAR,
INTFIELD00      INTEGER,
INTFIELD01      INTEGER,
INTFIELD02      INTEGER,
INTFIELD03      INTEGER,
INTFIELD04      INTEGER,
INTFIELD05      INTEGER,
INTFIELD06      INTEGER,
INTFIELD07      INTEGER,
INTFIELD08      INTEGER,
INTFIELD09      INTEGER,
INTFIELD10      INTEGER,
DOUBLEFIELD00   REAL,
DOUBLEFIELD01   REAL,
DOUBLEFIELD02   REAL,
DOUBLEFIELD03   REAL,
DOUBLEFIELD04   REAL,
DOUBLEFIELD05   REAL,
DOUBLEFIELD06   REAL,
DOUBLEFIELD07   REAL,
DOUBLEFIELD08   REAL,
DOUBLEFIELD09   REAL,
DOUBLEFIELD10   REAL
);

CREATE TABLE SYSNAME (
    NAME VARCHAR PRIMARY KEY NOT NULL,
    HBDATAVERID INTEGER,
    CONSTRAINT FK_HBDATAVERID FOREIGN KEY(HBDATAVERID)
        REFERENCES HANDBOOK(HBDATAVERID)
);